"""
amf.dpas.constraints
====================

DPAS — Discrete Positional Alignment System
--------------------------------------------

The DPAS is the core formal model of AMF v4.0. It is a **hypothesis** about
the generative structure of Voynichese tokens.

WHAT DPAS IS
------------
DPAS models Voynichese tokens as sequences generated by a small set of
positional slot rules. The hypothesis is that Voynichese words are not
arbitrary character strings but follow reproducible positional constraints
analogous to a morphophonological template.

This is motivated by the empirical observation (Currier 1976; Landini 2001)
that Voynichese tokens exhibit:
  1. Restricted character-position distributions (some characters appear
     almost exclusively in initial, medial, or final positions)
  2. Low type entropy relative to token count
  3. A small set of "core" recurring morpheme-like substrings

WHAT DPAS IS NOT
----------------
DPAS is NOT:
  - A proven linguistic grammar
  - A decipherment key
  - A mapping to any specific language

DPAS is a **constraint model**. It defines what tokens are "well-formed"
under the hypothesis. It makes the following falsifiable predictions:

  1. A high fraction of EVA corpus tokens should be DPAS-valid
     (if not, the constraint model is wrong or incomplete)
  2. DPAS-invalid tokens should be attributable to transcription
     uncertainty, damage, or scribal error
  3. Sections with different visual content should show different
     distributions of DPAS slot usage

FORMAL STRUCTURE
----------------
A DPAS token has the template:

    [ PREFIX? ] [ GALLOWS? ] [ CORE ] [ SUFFIX? ] [ TERMINAL? ]

Where each slot has a permitted character set and optionality rules.

Slot definitions are based on analysis of the top-frequency EVA token
families documented in Landini (2001) and Stolfi (2004). They are
**provisional** — the slot definitions may require revision as corpus
analysis proceeds.

VALIDATION AND FALSIFIABILITY
------------------------------
The DPAS constraint model is falsifiable in the following senses:

  1. COVERAGE: If fewer than X% of corpus tokens are DPAS-valid,
     the model is falsified (X is defined in COVERAGE_THRESHOLD below).
     Current threshold: 70% — conservative, acknowledging uncertainty.

  2. BOUNDARY PREDICTION: If DPAS predicts token X should not appear
     at line-initial position but it frequently does, a specific
     constraint is falsified.

  3. INTER-SECTION CONSISTENCY: If DPAS constraints do not differentiate
     manuscript sections, the model adds no explanatory value.

These are tested in amf.dpas.validator and amf.validation.pipeline.

REFERENCES
----------
Currier, P.H. (1976). Papers on the Voynich Manuscript. NSA Technical Report.

Landini, G. (2001). Evidence for the regular structure of glyphs in the
  Voynich manuscript. Cryptologia, 25(3), 153–165.

Stolfi, J. (2004). How Voynichese Words Are Formed. Technical note.
  Available: https://www.ic.unicamp.br/~stolfi/voynich/

Guy, J.B.M. (1991). Statistical properties of two Voynich manuscripts.
  Cryptologia, 15(3), 207–218.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


# ---------------------------------------------------------------------------
# EVA character class definitions
# ---------------------------------------------------------------------------
# These are derived from positional analysis of the EVA corpus.
# They are PROVISIONAL — subject to revision as corpus analysis proceeds.

class CharClass(str, Enum):
    """Named character classes used in DPAS slot definitions."""

    # Gallows characters: structurally tall glyphs. Almost always appear
    # in specific positions within tokens.
    GALLOWS = "gallows"

    # Bench characters: glyphs with descenders.
    BENCH = "bench"

    # Vowel-like: EVA characters appearing in medial positions with
    # frequency profiles similar to vowels in natural language.
    VOWEL_LIKE = "vowel_like"

    # Body characters: most common EVA characters, appear across positions.
    BODY = "body"

    # Prefix characters: characters that appear predominantly in
    # token-initial position.
    PREFIX = "prefix"

    # Suffix characters: characters that appear predominantly in
    # token-final position.
    SUFFIX = "suffix"


# Character class memberships (PROVISIONAL — based on Landini 2001 and
# Stolfi 2004 analyses)
CHAR_CLASSES: dict[str, set[str]] = {
    CharClass.GALLOWS: {"k", "t", "p", "f"},
    CharClass.BENCH: {"d", "g"},           # 'd', 'g' appear with bench-like structure
    CharClass.VOWEL_LIKE: {"a", "o", "e", "i"},
    CharClass.PREFIX: {"d", "s", "l", "q"},
    CharClass.SUFFIX: {"y", "m", "n", "r"},
    CharClass.BODY: {"ch", "sh", "cth", "ckh", "cph", "cfh",
                     "o", "a", "ee", "eee", "ii", "iii",
                     "ol", "or", "al", "ar", "in", "an"},
}

# The base EVA multigraph components (digraphs and trigraphs commonly
# treated as units in the literature)
EVA_MULTIGRAPHS: frozenset[str] = frozenset([
    "ch", "sh", "cth", "ckh", "cph", "cfh",
    "ee", "eee", "ii", "iii",
    "ol", "or", "al", "ar",
])


# ---------------------------------------------------------------------------
# DPAS Slot definitions
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class DPASSlot:
    """
    A single positional slot in the DPAS template.

    Attributes
    ----------
    name : str
        Slot identifier (e.g. "prefix", "gallows", "core").
    permitted : frozenset[str]
        Set of EVA characters/multigraphs permitted in this slot.
    optional : bool
        Whether this slot may be absent.
    max_repeat : int
        Maximum number of times this slot's content may be repeated.
        (Handles e.g. "eee" as three "e" vowel-like units.)
    description : str
        Human-readable description of this slot's role.
        Note: descriptions are HYPOTHESES about function, not proven facts.
    """
    name: str
    permitted: frozenset[str]
    optional: bool = True
    max_repeat: int = 1
    description: str = ""


# DPAS template: ordered list of slots
# This constitutes the formal hypothesis. It is testable against the corpus.
DPAS_TEMPLATE: list[DPASSlot] = [

    DPASSlot(
        name="prefix",
        permitted=frozenset(["d", "s", "l", "q", "o"]),
        optional=True,
        max_repeat=1,
        description=(
            "HYPOTHESIS: Initial characters that may function as prefixes or "
            "determiners. 'q' is almost exclusively line-initial in certain "
            "sections. Status: PROVISIONAL — based on frequency patterns only."
        ),
    ),

    DPASSlot(
        name="gallows",
        permitted=frozenset(["k", "t", "p", "f",
                              "ck", "ct", "cp", "cf",    # bench-mounted gallows
                              "sk", "st", "sp", "sf"]),
        optional=True,
        max_repeat=1,
        description=(
            "HYPOTHESIS: Gallows characters occupy a structurally prominent "
            "position. Their restricted positional distribution suggests a "
            "constrained role. 'Bench-mounted' variants (ck, ct, ...) are "
            "treated as single units following Stolfi (2004). PROVISIONAL."
        ),
    ),

    DPASSlot(
        name="core",
        permitted=frozenset([
            "o", "a", "e", "i",
            "ch", "sh",
            "ol", "or", "al", "ar",
            "ee", "eee", "ii", "iii",
            "ain", "aiin", "aiiin",
        ]),
        optional=False,     # Core is REQUIRED — a token must have a core
        max_repeat=2,
        description=(
            "The required central element. High-frequency core units "
            "include 'ch', 'sh', 'o', 'a', and vowel sequences 'ee*', 'ii*'. "
            "The 'ain/aiin/aiiin' series is a frequently recurring unit of "
            "unknown function. PROVISIONAL characterisation."
        ),
    ),

    DPASSlot(
        name="suffix",
        permitted=frozenset([
            "y", "m", "n", "r", "l",
            "in", "an", "on",
            "s",
        ]),
        optional=True,
        max_repeat=1,
        description=(
            "HYPOTHESIS: Terminal characters that may function as suffixes. "
            "'y' is the single most common line-final character in many "
            "sections. Whether this reflects a grammatical suffix, a cipher "
            "artifact, or a scribal convention is unknown. PROVISIONAL."
        ),
    ),
]


# ---------------------------------------------------------------------------
# Validation result
# ---------------------------------------------------------------------------

@dataclass
class DPASValidationResult:
    """
    Result of validating a single token against the DPAS template.

    Attributes
    ----------
    token : str
        The input EVA token.
    is_valid : bool
        Whether the token satisfies the DPAS template.
    matched_slots : list[str]
        Which slots were matched (for valid tokens).
    failure_reason : Optional[str]
        Human-readable reason for invalidity (for invalid tokens).
    confidence : str
        Qualitative confidence level: "high", "medium", "low".
        Reflects known ambiguities in EVA segmentation for this token.
    notes : str
        Additional notes, e.g. if the token contains uncertainty markers.
    """
    token: str
    is_valid: bool
    matched_slots: list[str]
    failure_reason: Optional[str] = None
    confidence: str = "medium"
    notes: str = ""


# Coverage threshold: the minimum fraction of corpus tokens that must be
# DPAS-valid for the model to be considered non-trivially applicable.
# Set conservatively at 70% to account for transcription uncertainty,
# scribal variation, and model incompleteness.
# If coverage falls below this threshold, the DPAS model is falsified
# in its current form.
COVERAGE_THRESHOLD: float = 0.70

COVERAGE_NOTE: str = (
    f"The DPAS coverage threshold is set at {COVERAGE_THRESHOLD:.0%}. "
    "If fewer than this fraction of corpus tokens are classified as DPAS-valid, "
    "the constraint model in its current form must be revised or rejected. "
    "This threshold is a design choice, not a statistical guarantee — it is "
    "set conservatively to allow for transcription noise and model incompleteness."
)
